name: Build

on:
  push:
    branches:
      - "main"

  pull_request:
    branches:
      - "*"

# Cancel in progress runs for PRs but not main
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  LLVM_PASTA_VER: b9e223f
  LLVM_VER: 18
  PYTHON_VER: 3.12
  UBUNTU_CODENAME: jammy
  CMAKE_VER: 3.26

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write

    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.4"

      - name: Use Python
        run: python --version

      - name: Install LLVM
        uses: trail-of-forks/install-llvm-action@master
        with:
          version: "18.1.3"

      - name: Use LLVM
        run: clang --version

      - name: Install CMake
        uses: trail-of-forks/actions-setup-cmake@master
        with:
          cmake-version: "3.26.x"

      - name: Use CMake
        run: cmake --version

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - run: git config --global --add safe.directory '*'

      - name: Set up variables
        run: |
          echo "RELEASE_DIR=${RUNNER_TEMP}/release" >> $GITHUB_ENV
          echo "LLVM_PREFIX_DIR=${RUNNER_TEMP}/llvm" >> $GITHUB_ENV
          echo "VERSION=$(git rev-parse --short=7 HEAD)" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=multiplier-$(git rev-parse --short=7 HEAD).tar.xz" >> $GITHUB_ENV

      - name: Install llvm-pasta
        run: |
          mkdir -p ${RELEASE_DIR}
          mkdir -p ${LLVM_PREFIX_DIR}
          gh release download ${LLVM_PASTA_VER} --repo trail-of-forks/llvm-project --pattern 'llvm-*'
          tar -xvJf llvm-pasta-*.tar.xz -C ${LLVM_PREFIX_DIR}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: |

          CXXFLAGS="-g0" \
          CCFLAGS="-g0" \
          cmake \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=${RELEASE_DIR} \
            -DCMAKE_EXE_LINKER_FLAGS="--ld-path=$(which ld.lld-${LLVM_VER})" \
            -DCMAKE_MODULE_LINKER_FLAGS="--ld-path=$(which ld.lld-${LLVM_VER})" \
            -DCMAKE_SHARED_LINKER_FLAGS="--ld-path=$(which ld.lld-${LLVM_VER})" \
            -DCMAKE_C_COMPILER="$(which clang-${LLVM_VER})" \
            -DCMAKE_CXX_COMPILER="$(which clang++-${LLVM_VER})" \
            -DClang_DIR=${LLVM_PREFIX_DIR}/lib/cmake/clang \
            -DLLVM_DIR=${LLVM_PREFIX_DIR}/lib/cmake/llvm \
            -DMLIR_DIR=${LLVM_PREFIX_DIR}/lib/cmake/mlir \
            -DMX_USE_VENDORED_CLANG=OFF \
            -DLLVM_ENABLE_LLD:BOOL=TRUE \
            -GNinja \
            ./

          ninja install

      # Release on merge to main
      - name: Package Release
        if: github.ref == 'refs/heads/main'
        working-directory: ${{ env.RELEASE_DIR }}
        run: tar --use-compress-program pixz -cf "${ARTIFACT_NAME}" *

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        run: gh release create ${VERSION} --generate-notes ${{ env.RELEASE_DIR }}/${{ env.ARTIFACT_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
